apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedConfigMap
metadata:
  name: kubevirt-config
  namespace: kubevirt
spec:
  template:
    data:
      debug.useEmulation: true
      feature-gates: LiveMigration,DataVolumes
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedConfigMapPlacement
metadata:
  name: kubevirt-config
  namespace: kubevirt
spec:
  clusterNames:
  - cluster1
  - cluster2
---
